"""Builds bench/RESULTS.md from every bench/results/*.jsonl file.

Usage: python -m bench.report
"""
import glob
import json
import os
from collections import defaultdict
from datetime import date

from bench.tasks import TASKS

BENCH_DIR = os.path.dirname(os.path.abspath(__file__))


def load_results() -> dict[str, list[dict]]:
    by_config: dict[str, list[dict]] = defaultdict(list)
    for path in sorted(glob.glob(os.path.join(BENCH_DIR, "results", "*.jsonl"))):
        with open(path, encoding="utf-8") as f:
            for line in f:
                record = json.loads(line)
                if not record["pipeline"].get("quota_exhausted"):
                    by_config[record["config"]["name"]].append(record)
    return by_config


def _solved(r: dict) -> bool:
    return r["hidden"]["passed"] == r["hidden"]["total"]


def _claimed_done(r: dict) -> bool:
    """The pipeline reported success: finished cleanly, every planned task done."""
    p = r["pipeline"]
    return not p.get("error") and p.get("tasks_planned", 0) > 0 and p.get("tasks_done") == p.get("tasks_planned")


def summarize(records: list[dict]) -> dict:
    n = len(records)
    claimed = [r for r in records if _claimed_done(r)]
    avg = lambda key: sum(r["pipeline"].get(key) or 0 for r in records) / n  # noqa: E731
    return {
        "runs": n,
        "solved": sum(map(_solved, records)),
        "check_rate": sum(r["hidden"]["passed"] for r in records) / sum(r["hidden"]["total"] for r in records),
        "claimed": len(claimed),
        "false_done": sum(not _solved(r) for r in claimed),
        "errors": sum(bool(r["pipeline"].get("error")) for r in records),
        "qa_rejections": avg("qa_rejections"),
        "testing_failures": avg("testing_failures"),
        "llm_calls": avg("llm_calls"),
        "tokens": avg("prompt_tokens") + avg("completion_tokens"),
        "seconds": avg("seconds"),
    }


def render(by_config: dict[str, list[dict]]) -> str:
    lines = [
        "# Benchmark results",
        "",
        f"_Generated by `python -m bench.report` on {date.today().isoformat()}. "
        "Every number below comes from `bench/results/*.jsonl`._",
        "",
        f"{len(TASKS)} tasks ({', '.join(f'{d}: {sum(t.difficulty == d for t in TASKS)}' for d in ('easy', 'medium', 'hard'))}), "
        f"{sum(len(t.cases) for t in TASKS)} hidden test cases in total. A task is **solved** when the "
        "generated code passes every one of its hidden tests. The pipeline never sees these tests — "
        "see `bench/tasks.py`.",
        "",
        "**False \"done\"** counts runs where the pipeline finished with every task marked done by QA, "
        "yet the code fails at least one hidden test — i.e. how often the team's own review was wrong.",
        "",
        "| Config | Model | Testing Agent | Runs | Solved | Hidden tests passed | Pipeline said done | False \"done\" | QA rejections / run | LLM calls / run | Tokens / run | Time / run |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for name, records in by_config.items():
        s, cfg = summarize(records), records[0]["config"]
        lines.append(
            f"| {name} | `{cfg['model']}` | {cfg['testing_agent']} | {s['runs']} | "
            f"**{s['solved']}/{s['runs']}** ({s['solved'] / s['runs']:.0%}) | {s['check_rate']:.0%} | "
            f"{s['claimed']}/{s['runs']} | {s['false_done']}/{s['claimed']} | {s['qa_rejections']:.1f} | "
            f"{s['llm_calls']:.1f} | {s['tokens'] / 1000:.1f}k | {s['seconds']:.0f}s |"
        )

    lines += ["", "## Per task (hidden tests passed / total)", "",
              "| Task | Difficulty | " + " | ".join(by_config) + " |",
              "|---|---|" + "---|" * len(by_config)]
    for task in TASKS:
        cells = []
        for records in by_config.values():
            runs = [r for r in records if r["task"] == task.id]
            cells.append(", ".join(f"{r['hidden']['passed']}/{r['hidden']['total']}" + (" ✓" if _solved(r) else "")
                                   for r in runs) or "—")
        lines.append(f"| {task.id} | {task.difficulty} | " + " | ".join(cells) + " |")

    errors = [(name, r["task"], r["pipeline"]["error"]) for name, rs in by_config.items()
              for r in rs if r["pipeline"].get("error")]
    if errors:
        lines += ["", "## Runs that ended in an error", ""]
        lines += [f"- **{name} / {task}**: {err[:200]}" for name, task, err in errors]
    return "\n".join(lines) + "\n"


def main():
    by_config = load_results()
    if not by_config:
        print("No results yet — run `python -m bench.run ...` first.")
        return
    out = os.path.join(BENCH_DIR, "RESULTS.md")
    with open(out, "w", encoding="utf-8") as f:
        f.write(render(by_config))
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
